# Generated by Django 5.2.4 on 2025-07-23 10:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Portfolio', max_length=100)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=7)),
                ('cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('performance_cache', models.JSONField(blank=True, null=True)),
                ('last_calc_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('CASH_IN', 'Cash In'), ('CASH_OUT', 'Cash Out'), ('SHORT_COVER', 'Short Cover')], max_length=12)),
                ('ticker', models.CharField(blank=True, max_length=15)),
                ('quantity', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('cash_delta', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='portfolios.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=15)),
                ('quantity', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('avg_cost', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='portfolios.portfolio')),
            ],
            options={
                'unique_together': {('portfolio', 'ticker')},
            },
        ),
    ]
