# Generated by Django 5.2.4 on 2025-07-23 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={},
        ),
        migrations.AlterField(
            model_name='trade',
            name='quantity',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
