# Generated by Django 5.2.4 on 2025-07-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TickerInfo',
            fields=[
                ('ticker', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('pe', models.FloatField(blank=True, null=True)),
                ('eps', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=15)),
                ('date', models.DateField()),
                ('close', models.DecimalField(decimal_places=4, max_digits=18)),
                ('dividend', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('split', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
            ],
            options={
                'ordering': ['ticker', 'date'],
                'unique_together': {('ticker', 'date')},
            },
        ),
    ]
